Added: item model, user model, itemDto, userDto, itemRepos, userRepos…
Irina-Kucherenko/java-shareit pull request #1
Opened 2024-08-06 18:34 UTC by Irina-Kucherenko

…, userService, itemService, user Controller, item Controller

2024-08-07 23:41 UTC, mikita95 requested changes
Все сделано просто отлично :) Оставил лишь небольшие рекомендации

2024-08-07 23:41 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        if (checkUser(userId)) {
Сейчас метод имеет слишком большую вложенность, можно было бы использовать safe guard, или как то ещё упростить логику

2024-08-07 23:41 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +    static final String USER_NOT_FOUND = "User not found";
Может быть private

2024-08-08 21:10 UTC, Irina-Kucherenko commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        if (checkUser(userId)) {
Честно, не очень поняла, что вы имеете в виду под safe guard. Да и в интернете подобного ничего не нашла

2024-08-09 04:03 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        if (checkUser(userId)) {
Ох, прошу прощения. Я имел в виду "охранное" выражение (guard expression).

2024-08-09 04:03 UTC, mikita95 approved these changes
Все сделано отлично :) Можно мержить пул-реквест

2024-08-12 13:54 UTC, merged